export const repositoryUrl =
  "https://github.com/chelokot/square-packing-archive";

export const copy = {
  title: "Square Packing Archive",
  heading: "Small squares. A surprisingly hard problem.",
  problemLabel: "Discrete geometry / squares in a square",
  introduction:
    "How small a square can contain n unit squares? Explore constructions, follow improvements, and read the proofs. Squares may rotate; their interiors cannot overlap.",
  skipNavigation: "Skip to the explorer",
  navigation: "Main navigation",
  explore: "Explore the packings",
  catalog: "Catalog",
  sources: "Sources & proofs",
  github: "GitHub",
  claimCount: "claims catalogued",
  exactCount: "exact results checked in Lean",
  layoutCount: "coordinate sets to explore",
  archiveScope: (date: string) => `Selected records · data updated ${date}`,
  noLayout: "Coordinates not yet in the archive",
  noRecord:
    "This n has no catalogued result yet. This does not mean the mathematical problem is unsolved.",
  layoutNotImported:
    "Results are catalogued below. An interactive reconstruction is still to be added.",
  readHistory: "Read the results for this n",
  viewLayout: (count: number) => `View n = ${count}`,
  history: "Results & history",
  boundHistory: "Improving upper bounds · selected historical records",
  codeLicense: "Code & Lean · Apache-2.0",
  dataLicense: "Archive data · CC BY 4.0",
  contribute: "Submit a result",
  matrixTitle: "Choose the number of squares",
  coverageOverviewTitle: "Packing results · 1–100 squares",
  coverageOverviewDescription:
    "Colors show evidence status. The symbols =, ≤ and ≥ distinguish exact results, upper bounds and lower bounds. Unmarked cells are not catalogued.",
  coverageOverviewScope:
    "Selected records · Color shows evidence; symbol shows the claim",
  claimRelations: {
    exact: "Exact",
    upper: "Upper bound",
    lower: "Lower bound",
  },
  matrixCellLabel: (count: number, description: string) =>
    `n = ${count}: ${description}`,
  squareCount: "Number of squares",
  previous: "Previous n",
  next: "Next n",
  availableLayouts: "With coordinates",
  emptyStatus: "Not catalogued",
  verified: "Lean verified",
  published: "Published · awaiting Lean",
  computed: "Computed · awaiting Lean",
  reported: "Reported",
  matrixVerified: "Lean checked",
  matrixPublished: "Published proof",
  matrixComputed: "Computed",
  matrixReported: "Reported",
  viewerTitle: (count: number) => `${count} unit squares`,
  containerSide: "Container side",
  layoutBound: "This layout gives an upper bound, not a proof of optimality.",
  viewHelp: "Drag to pan · scroll to zoom · select a square to inspect",
  angleGroups: "Orientation groups",
  angleGroupHelp:
    "Angles grouped to the nearest 0.5°. Toggle a group to hide it.",
  inspectPrompt: "Select a square in the drawing or use the square selector.",
  selectSquare: "Inspect square",
  noSquare: "Choose a square",
  square: (id: number) => `Square ${id}`,
  centerX: "Center x",
  centerY: "Center y",
  exactCoordinates: "Exact rational coordinates",
  tangent: "Exact t = tan(θ/2)",
  cosine: "Exact cos θ",
  sine: "Exact sin θ",
  showLabels: "Square numbers",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  rotateLeft: "Rotate left",
  rotateRight: "Rotate right",
  resetView: "Reset view",
  download: "Download coordinates",
  drawingLabel: (count: number) => `Packing of ${count} unit squares`,
  catalogTitle: "The catalog",
  catalogDescription:
    "Published results and formal proofs, with their original attribution. The catalog is still being expanded.",
  search: "Search n, author, year or value",
  statusFilter: "Filter by evidence",
  allEvidence: "All evidence",
  resultCount: (visible: number, total: number) =>
    `${visible} of ${total} active claims`,
  noMatches: "No matching claims. Try another search or evidence filter.",
  columns: {
    count: "n",
    claim: "Result",
    date: "Year",
    contributors: "Contributors",
    status: "Evidence",
    links: "Read",
  },
  elementary: "Elementary construction",
  source: "Source",
  proof: "Lean proof",
  historyTitle: (count: number) => `The record for n = ${count}`,
  noHistory: "No results catalogued for this n yet.",
  historical: "Historical",
  current: "Active claim",
  coverageTitle: "How much is proved?",
  coverageDescription:
    "Distinct n with an exact result in this catalog. Formal checks are dated when they were added, separately from publication.",
  coveragePublished: "Published exact results",
  coverageVerified: "Exact results checked in Lean",
  coverageData: "Show yearly counts",
  proofTitle: "What a checked result means",
  proofDescription:
    "A green label means the stated bound or equality has a Lean theorem checked by the kernel. A published proof awaiting formalization keeps its own label. An upper-bound proof does not establish optimality.",
  proofLink: "Read the Lean library",
  sourcesTitle: "Built on the work of others",
  sourcesDescription:
    "The surveys and record trackers below are the foundations of this archive. Each result links to its contributors and source; publications retain their own licenses.",
  dataLink: "Download the archive",
} as const;
