export const repositoryUrl =
  "https://github.com/chelokot/square-packing-archive";

export const copy = {
  title: "Square Packing Archive",
  introduction:
    "How small a square can contain n unit squares? Rotation is allowed; interiors cannot overlap.",
  skipNavigation: "Skip to the explorer",
  navigation: "Main navigation",
  explore: "Explore the packings",
  catalog: "Catalog",
  sources: "Sources & proofs",
  github: "GitHub",
  exactCount: "proved optimal",
  archiveScope: (date: string) => `Data updated ${date}`,
  noLayout: "Coordinates not yet in the archive",
  noRecord:
    "This n has no catalogued result yet. This does not mean the mathematical problem is unsolved.",
  layoutNotImported:
    "Results are catalogued below. An interactive reconstruction is still to be added.",
  readHistory: "Read the results for this n",
  viewLayout: (count: number) => `View n = ${count}`,
  history: "Results & history",
  boundHistory: "Improving upper bounds · selected historical records",
  codeLicense: "Code & Lean · Apache-2.0",
  dataLicense: "Archive data · CC BY 4.0",
  contribute: "Submit a result",
  matrixTitle: "Choose the number of squares",
  coverageOverviewTitle: "Packing results · 1–100 squares",
  coverageOverviewDescription:
    "Green cells mark proved optima. White cells mark bounds only. Every result has a Lean proof.",
  coverageOverviewScope:
    "Selected records + basic grid bounds · Green: proved optimal · White: bound only",
  claimRelations: {
    exact: "Exact",
    upper: "Upper bound",
    lower: "Lower bound",
  },
  matrixCellLabel: (count: number, description: string) =>
    `n = ${count}: ${description}`,
  matrixExact: "Proved optimal",
  matrixBound: "Bound only",
  gridBaseline: "Basic grid bound",
  emptyStatus: "Not catalogued",
  viewerTitle: (count: number) => `${count} unit squares`,
  containerSide: "Container side",
  viewerHelp: "Viewer help",
  viewHelp: "Drag to pan · scroll to zoom · select a square to inspect",
  angleGroups: "Orientation groups",
  angleGroupHelp:
    "Angles grouped to the nearest 0.5°. Toggle a group to hide it.",
  inspectPrompt: "Select a square in the drawing or use the square selector.",
  selectSquare: "Inspect square",
  noSquare: "Choose a square",
  square: (id: number) => `Square ${id}`,
  centerX: "Center x",
  centerY: "Center y",
  exactCoordinates: "Exact coordinates",
  tangent: "Exact t = tan(θ/2)",
  cosine: "Exact cos θ",
  sine: "Exact sin θ",
  showLabels: "Square numbers",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  rotateLeft: "Rotate left",
  rotateRight: "Rotate right",
  resetView: "Reset view",
  download: "Download coordinates",
  drawingLabel: (count: number) => `Packing of ${count} unit squares`,
  catalogTitle: "The catalog",
  catalogDescription:
    "Formalized results with their original attribution. The historical catalog is still being expanded.",
  search: "Search n, author, year or value",
  resultCount: (visible: number, total: number) =>
    `${visible} of ${total} active claims`,
  noMatches: "No matching claims. Try another search.",
  columns: {
    count: "n",
    claim: "Result",
    date: "Year",
    contributors: "Contributors",
    links: "Read",
  },
  elementary: "Elementary construction",
  source: "Source",
  proof: "Lean proof",
  historyTitle: (count: number) => `The record for n = ${count}`,
  noHistory: "No results catalogued for this n yet.",
  historical: "Historical",
  current: "Active claim",
  coverageTitle: "How much is proved?",
  coverageDescription:
    "Distinct n with an exact result in this catalog. Formal checks are dated when they were added, separately from publication.",
  coveragePublished: "Published exact results",
  coverageVerified: "Formalized exact results",
  coverageData: "Show yearly counts",
  proofTitle: "Every result has a proof",
  proofDescription:
    "Every result in this archive requires a kernel-checked Lean proof. Green cells mark proved optima; white cells mark bounds only. Results awaiting formalization belong in GitHub issues.",
  pendingResults: "Pending results & contributions",
  proofLink: "Read the Lean library",
  sourcesTitle: "Built on the work of others",
  sourcesDescription:
    "The surveys and record trackers below are the foundations of this archive. Each result links to its contributors and source; publications retain their own licenses.",
  dataLink: "Download the archive",
} as const;
