import SquarePackingArchive.Records.Basic
import SquarePackingArchive.Records.SquareNumbers
import SquarePackingArchive.Records.NearSquare
import SquarePackingArchive.Records.Square5
import SquarePackingArchive.Records.Square8
import SquarePackingArchive.Records.Square11
import SquarePackingArchive.Records.Square68
import SquarePackingArchive.Records.Square69
import SquarePackingArchive.Records.HistoricalUpperBounds
import SquarePackingArchive.Unavoidable
import SquarePackingArchive.Friedman
import SquarePackingArchive.Resource
import SquarePackingArchive.NagamochiResource
import SquarePackingArchive.NagamochiLemmas
import SquarePackingArchive.NagamochiCanonicalTerminal
import SquarePackingArchive.Nagamochi

#print axioms SquarePackingArchive.Records.Basic.s1_eq_one
#print axioms SquarePackingArchive.Records.SquareNumbers.squareNumber_isMinimumSide
#print axioms SquarePackingArchive.Records.SquareNumbers.s4_eq_two
#print axioms SquarePackingArchive.Records.SquareNumbers.s9_eq_three
#print axioms SquarePackingArchive.Records.SquareNumbers.s16_eq_four
#print axioms SquarePackingArchive.Records.SquareNumbers.s25_eq_five
#print axioms SquarePackingArchive.Records.SquareNumbers.s36_eq_six
#print axioms SquarePackingArchive.Records.SquareNumbers.s49_eq_seven
#print axioms SquarePackingArchive.Records.SquareNumbers.s64_eq_eight
#print axioms SquarePackingArchive.Records.SquareNumbers.s81_eq_nine
#print axioms SquarePackingArchive.Records.NearSquare.s2_eq_two
#print axioms SquarePackingArchive.Records.NearSquare.s3_eq_two
#print axioms SquarePackingArchive.Records.Square5.s5_le_goebel
#print axioms SquarePackingArchive.Records.Square5.unavoidable_points
#print axioms SquarePackingArchive.Records.Square5.s5_ge_goebel
#print axioms SquarePackingArchive.Records.Square5.s5_eq_goebel
#print axioms SquarePackingArchive.Records.Square8.contains_bottomLeftCorner
#print axioms SquarePackingArchive.Records.Square8.contains_bottomRightPair
#print axioms SquarePackingArchive.Records.Square8.contains_leftPair
#print axioms SquarePackingArchive.PlacedSquare.contains_triangleVertex
#print axioms SquarePackingArchive.Records.Square8.points_unavoidable
#print axioms SquarePackingArchive.Records.Square8.s8_lower_bound
#print axioms SquarePackingArchive.Records.Square8.s8_eq_three
#print axioms SquarePackingArchive.Records.Square11TrumpRationalized.s11_le_3_88
#print axioms SquarePackingArchive.Records.Square68.s68_le_8_80339
#print axioms SquarePackingArchive.Records.Square69.s69_le_8_8272
#print axioms SquarePackingArchive.HasPacking.enlarge
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s12_le_four
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s11_le_goebel_1979
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s11_le_hamalainen_1980
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s68_le_brendberg_2023
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s68_le_schadt_ellsworth_2025
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s69_le_morandi_cantrell_2023
#print axioms SquarePackingArchive.PlacedSquare.rotateQuarter_contains_iff
#print axioms SquarePackingArchive.PlacedSquare.firstQuadrant_contains_iff
#print axioms SquarePackingArchive.Packing.side_positive
#print axioms SquarePackingArchive.Unavoidable.interior_scaled
#print axioms SquarePackingArchive.Packing.squareCount_le_of_interiorUnavoidable
#print axioms SquarePackingArchive.lowerBound_succ_of_interiorUnavoidable_below
#print axioms SquarePackingArchive.lowerBound_succ_of_unavoidable
#print axioms SquarePackingArchive.PlacedSquare.contains_unitCorner
#print axioms SquarePackingArchive.PlacedSquare.contains_cornerPoint
#print axioms SquarePackingArchive.PlacedSquare.contains_bottomPair
#print axioms SquarePackingArchive.PlacedSquare.contains_bottomPairWith
#print axioms SquarePackingArchive.Packing.squareCount_lt_resourceMass
#print axioms SquarePackingArchive.finiteFamily_card_lt_resourceMass
#print axioms SquarePackingArchive.NagamochiResource.measure_univ
#print axioms SquarePackingArchive.horizontalSegmentMeasure_lower_bound
#print axioms SquarePackingArchive.NagamochiResource.boundaryLines_subset_lower_bound
#print axioms SquarePackingArchive.NagamochiResource.innerArea_add_boundaryLines_le_measure
#print axioms SquarePackingArchive.NagamochiResource.cornerPoints_lower_bound_of_two_mem
#print axioms SquarePackingArchive.NagamochiResource.edgePoints_lower_bound_of_mem
#print axioms SquarePackingArchive.NagamochiResource.EdgePoint.cornerPoints_ne
#print axioms SquarePackingArchive.volume_rightTriangleProductRegion
#print axioms SquarePackingArchive.volume_rightTriangleRegion
#print axioms SquarePackingArchive.volume_translatedRightTriangleRegion
#print axioms SquarePackingArchive.volume_openTranslatedRightTriangleRegion
#print axioms SquarePackingArchive.openTranslatedRightTriangleRegion_subset_of_vertices_mem_closure
#print axioms SquarePackingArchive.volume_openOrientedTranslatedRightTriangleRegion
#print axioms SquarePackingArchive.openOrientedTranslatedRightTriangleRegion_subset_of_vertices_mem_closure
#print axioms SquarePackingArchive.closure_unitSquareInterior
#print axioms SquarePackingArchive.PlacedSquare.closure_interiorRegion
#print axioms SquarePackingArchive.PlacedSquare.mem_dilatedInteriorRegion_iff
#print axioms SquarePackingArchive.PlacedSquare.horizontalPoint_mem_swap_iff
#print axioms SquarePackingArchive.PlacedSquare.convex_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.dilatedCenterX_halfExtent_le
#print axioms SquarePackingArchive.PlacedSquare.dilatedCenterY_halfExtent_le
#print axioms SquarePackingArchive.PlacedSquare.unitCornerPoint_mem_dilatedInteriorRegion_of_center_le_one
#print axioms SquarePackingArchive.PlacedSquare.case5CornerPoints_mem_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.firstQuadrant_dilatedInteriorRegion_eq
#print axioms SquarePackingArchive.PlacedSquare.case5TopRightPoints_mem_dilatedInteriorRegion_any_frame
#print axioms SquarePackingArchive.PlacedSquare.horizontalCenterPoint_mem_dilatedInteriorRegion_any_frame
#print axioms SquarePackingArchive.PlacedSquare.topHorizontalCenterPoint_mem_dilatedInteriorRegion_any_frame
#print axioms SquarePackingArchive.PlacedSquare.rightVerticalCenterPoint_mem_dilatedInteriorRegion_any_frame
#print axioms SquarePackingArchive.PlacedSquare.horizontalChord_inside_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.horizontalAdjacentChord_inside_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.horizontalOtherAdjacentChord_inside_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.horizontalOtherAdjacentChord_length
#print axioms SquarePackingArchive.PlacedSquare.horizontalCosineChord_length_at_least_factor
#print axioms SquarePackingArchive.PlacedSquare.horizontalSineChord_length_at_least_factor
#print axioms SquarePackingArchive.PlacedSquare.verticalSineChord_length_at_least_factor
#print axioms SquarePackingArchive.PlacedSquare.verticalCosineChord_length_at_least_factor
#print axioms SquarePackingArchive.Nagamochi.adjacentCut_triangleArea_lt_half_chord
#print axioms SquarePackingArchive.Nagamochi.centeredAdjacentChordLength_gt_one
#print axioms SquarePackingArchive.Nagamochi.Frame.exists_tangentHalfAngle_of_sine_le_cosine
#print axioms SquarePackingArchive.Nagamochi.horizontalAdjacentChord_length_gt_one
#print axioms SquarePackingArchive.Nagamochi.horizontalAdjacentChord_length_gt_one_any_positive_frame
#print axioms SquarePackingArchive.Nagamochi.cornerAdjacentChordLength_gt_one
#print axioms SquarePackingArchive.Nagamochi.horizontalOtherAdjacentChord_length_gt_one_of_bottom_contained
#print axioms SquarePackingArchive.Nagamochi.horizontalOtherAdjacentChord_length_gt_one
#print axioms SquarePackingArchive.Nagamochi.horizontalOtherAdjacentChord_length_gt_one_any_positive_frame
#print axioms SquarePackingArchive.Nagamochi.cornerCut_area_add_half_chord_gt_half
#print axioms SquarePackingArchive.Nagamochi.pinnedCut_score_gt_one
#print axioms SquarePackingArchive.Nagamochi.innerArea_lower_bound_of_translatedRightTriangle
#print axioms SquarePackingArchive.Nagamochi.innerArea_lower_bound_of_openTranslatedRightTriangle
#print axioms SquarePackingArchive.Nagamochi.innerArea_lower_bound_of_openOrientedTranslatedRightTriangle
#print axioms SquarePackingArchive.Nagamochi.pinnedCutTriangleRegion_subset_interiorRegion
#print axioms SquarePackingArchive.Nagamochi.pinnedCut_innerArea_lower_bound_of_triangle
#print axioms SquarePackingArchive.Nagamochi.PinnedCutTriangleWitness.innerArea_lower_bound
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_real_grouped_bounds
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_pinned_cut_bounds
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_pinned_cut_triangle_and_boundary_bound
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_pinned_cut_witness_and_boundary_bound
#print axioms SquarePackingArchive.Nagamochi.canonicalPinned_score_gt_one
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case6_corner_cut_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.boundaryChord_of_pointAt_mem
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_long_and_short_boundary_chords_and_corner_point
#print axioms SquarePackingArchive.Nagamochi.exists_nat_in_open_interval_of_length_gt_one
#print axioms SquarePackingArchive.Nagamochi.openGridChord_endpoint_bounds
#print axioms SquarePackingArchive.Nagamochi.longGridChordWitness_of_open_chord
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_centered_horizontalAdjacent
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_bottom_touching_horizontalOtherAdjacent
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_horizontalOpposite
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_axis_aligned
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_center_in_bottom_strip
#print axioms SquarePackingArchive.Nagamochi.topLongGridChordWitness_of_center_in_top_strip
#print axioms SquarePackingArchive.Nagamochi.leftLongGridChordWitness_of_center_in_left_strip
#print axioms SquarePackingArchive.Nagamochi.rightLongGridChordWitness_of_center_in_right_strip
#print axioms SquarePackingArchive.Nagamochi.gridPointWitness_of_open_grid_chord
#print axioms SquarePackingArchive.Nagamochi.bottomGridPointWitness_of_center_in_bottom_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.gridPointWitness_of_center_in_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_edge_strip_long_chord_and_connections
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_edge_strip_long_chord_without_grid_corners
#print axioms SquarePackingArchive.Nagamochi.corner_mem_of_gridPointWitness_of_no_edge_points
#print axioms SquarePackingArchive.Nagamochi.edge_mem_of_gridPointWitness_of_no_corner_points
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_dilatedInteriorRegion_subset_innerArea
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_compensated_inner_area
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case5_resource_bounds
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_unitCornerPoint_mem
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case5_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case5_any_frame
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case5
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_bottom_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_top_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_left_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_right_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_resource_witness
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_two_boundary_corner_points
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_first_boundary_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_second_boundary_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_long_chord_and_grid_point
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_long_chord_and_boundary_connection
#print axioms SquarePackingArchive.Nagamochi.firstBoundaryCornerConnection_of_mem
#print axioms SquarePackingArchive.Nagamochi.secondBoundaryCornerConnection_of_mem
#print axioms SquarePackingArchive.Nagamochi.case7EdgeStripOutcome_of_long_chord
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_opposite_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_bottom_opposite_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_first_boundary_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_second_boundary_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_bottom_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_two_boundary_corner_points_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_both_bottom_corner_points_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_two_boundaryLine_chords
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_half_area_and_boundary_chord
#print axioms SquarePackingArchive.Nagamochi.boundaryChord_of_opposite
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_two_opposite_boundary_chords
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case3_resource_witness
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_bottom_top_horizontalOpposite
#print axioms SquarePackingArchive.Packing.squareCount_lt_nagamochiMass
#print axioms SquarePackingArchive.Records.NearSquare.squareMinusTwo_isMinimumSide_of_nagamochiScores
