import SquarePackingArchive.Records.Basic
import SquarePackingArchive.Records.SquareNumbers
import SquarePackingArchive.Records.NearSquare
import SquarePackingArchive.Records.Square5
import SquarePackingArchive.Records.Square6
import SquarePackingArchive.Records.Square13
import SquarePackingArchive.Records.Square10
import SquarePackingArchive.Records.Square33
import SquarePackingArchive.Records.Square22
import SquarePackingArchive.Records.Square8
import SquarePackingArchive.Records.Square15
import SquarePackingArchive.Records.Square24
import SquarePackingArchive.Records.Square23
import SquarePackingArchive.Records.Square34
import SquarePackingArchive.Records.Square46
import SquarePackingArchive.Records.Square11
import SquarePackingArchive.Records.Square68
import SquarePackingArchive.Records.Square69
import SquarePackingArchive.Records.HistoricalUpperBounds
import SquarePackingArchive.Unavoidable
import SquarePackingArchive.GridObstruction
import SquarePackingArchive.Friedman
import SquarePackingArchive.FriedmanStrip
import SquarePackingArchive.MovingUnavoidable
import SquarePackingArchive.StromquistPentagon
import SquarePackingArchive.StromquistOwnership
import SquarePackingArchive.BentzExceptionalSquare
import SquarePackingArchive.BentzOrderedChords
import SquarePackingArchive.Rectangle
import SquarePackingArchive.Resource
import SquarePackingArchive.NagamochiResource
import SquarePackingArchive.NagamochiLemmas
import SquarePackingArchive.NagamochiHalfArea
import SquarePackingArchive.NagamochiCutSymmetry
import SquarePackingArchive.NagamochiInner
import SquarePackingArchive.NagamochiBoundaryAnchor
import SquarePackingArchive.NagamochiCapLowerBound
import SquarePackingArchive.NagamochiEdgeStripNoCorners
import SquarePackingArchive.NagamochiAugmented
import SquarePackingArchive.NagamochiGridSections
import SquarePackingArchive.NagamochiWeightObstruction
import SquarePackingArchive.NagamochiBadSquare
import SquarePackingArchive.NagamochiDoublePoint
import SquarePackingArchive.NagamochiPackingConstraints
import SquarePackingArchive.NagamochiBoundaryChain
import SquarePackingArchive.NagamochiChainGeometry
import SquarePackingArchive.NagamochiBoundaryPropagation
import SquarePackingArchive.NagamochiChainStep
import SquarePackingArchive.NagamochiEndpointResource
import SquarePackingArchive.NagamochiEdgeOwnership
import SquarePackingArchive.NagamochiInitialDebt
import SquarePackingArchive.NagamochiFiniteChain
import SquarePackingArchive.NagamochiCornerOwnership
import SquarePackingArchive.NagamochiCornerTerminalResource
import SquarePackingArchive.NagamochiBadPacking
import SquarePackingArchive.NagamochiPackingTheorem
import SquarePackingArchive.NagamochiInnerCorners
import SquarePackingArchive.NagamochiCounterexample
import SquarePackingArchive.NagamochiCanonicalTerminal
import SquarePackingArchive.Nagamochi

#print axioms SquarePackingArchive.Records.Basic.s1_eq_one
#print axioms SquarePackingArchive.Records.Square10.s10_le_goebel
#print axioms SquarePackingArchive.Records.Square33.s33_lower_bound
#print axioms SquarePackingArchive.Records.Square33.s33_eq_six
#print axioms SquarePackingArchive.Records.Square22.s22_lower_bound
#print axioms SquarePackingArchive.Records.Square22.s22_eq_five
#print axioms SquarePackingArchive.Packing.exists_closed_disjoint_family_in_larger_container
#print axioms SquarePackingArchive.Records.Square6.center_free_closed_family_has_two_matchings
#print axioms SquarePackingArchive.Records.Square6.SingletonPair.allowed
#print axioms SquarePackingArchive.Records.Square6.corner_pair_forces_corner
#print axioms SquarePackingArchive.Records.Square6.three_contacts_left_intercept
#print axioms SquarePackingArchive.PlacedSquare.contains_triangleVertex_of_cross_nonnegative
#print axioms SquarePackingArchive.Stromquist.lemma4_first
#print axioms SquarePackingArchive.Stromquist.lemma4_second
#print axioms SquarePackingArchive.Stromquist.lemma4_bentz_first
#print axioms SquarePackingArchive.Stromquist.lemma4_bentz_second
#print axioms SquarePackingArchive.Stromquist.lemma4_bentz_third
#print axioms SquarePackingArchive.Stromquist.lemma5
#print axioms SquarePackingArchive.Stromquist.TenPoints.unavoidable
#print axioms SquarePackingArchive.Stromquist.TenPoints.exists_namedFamily_of_packing_below
#print axioms SquarePackingArchive.Records.Square13.initialPoints_unavoidable
#print axioms SquarePackingArchive.Records.Square13.packing_has_two_corner_restricted_points
#print axioms SquarePackingArchive.Bentz.middle_exception_impossible
#print axioms SquarePackingArchive.Bentz.bottom_exception_impossible
#print axioms SquarePackingArchive.Bentz.vertical_unit_chord_of_center_le_eleven_tenths
#print axioms SquarePackingArchive.Bentz.count_lt_cutoff_of_unit_chords_below
#print axioms SquarePackingArchive.Bentz.count_lt_remaining_of_unit_chords_above
#print axioms SquarePackingArchive.PlacedSquare.AxisAligned.contains_interiorGridPoint
#print axioms SquarePackingArchive.Packing.covered_square_count_le_point_count
#print axioms SquarePackingArchive.Packing.gridAvoidingSquares_card_lower_bound
#print axioms SquarePackingArchive.Packing.gridAvoidingSquares_subset_tiltedSquares
#print axioms SquarePackingArchive.Packing.tiltedSquares_card_lower_bound
#print axioms SquarePackingArchive.Packing.sixtyTwo_requires_thirteen_tilted
#print axioms SquarePackingArchive.Packing.squareMinusTwo_requires_many_tilted
#print axioms SquarePackingArchive.Nagamochi.bottom_centerline_anchor
#print axioms SquarePackingArchive.Nagamochi.bottom_active_of_edge_strip
#print axioms SquarePackingArchive.Nagamochi.bottom_line_clipped_of_edge_strip_and_missing_corners
#print axioms SquarePackingArchive.Nagamochi.upperCap_le_innerArea_add_nonbottomCuts
#print axioms SquarePackingArchive.PlacedSquare.dilatedPoint_mem_closure
#print axioms SquarePackingArchive.Nagamochi.horizontalLowerCap_volume_lower_bound
#print axioms SquarePackingArchive.Nagamochi.horizontalUpperCap_volume_lower_bound
#print axioms SquarePackingArchive.Nagamochi.horizontalUpperCap_section_lower_bound
#print axioms SquarePackingArchive.Nagamochi.upperCap_area_add_half_section_gt_half_of_fits
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_bottom_adjacent_without_corners_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_bottom_adjacent_without_corners
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_bottom_strip_without_corners_nonnegative_frame
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_bottom_strip_without_corners
#print axioms SquarePackingArchive.Nagamochi.cap_score_gt_half_add_fifth_height
#print axioms SquarePackingArchive.Nagamochi.upperCap_vertical_projection_inside
#print axioms SquarePackingArchive.Nagamochi.upperCap_le_innerArea_add_narrow_strip_loss
#print axioms SquarePackingArchive.Nagamochi.area_add_half_bottom_line_gt_half_of_bottom_strip_missing_horizontal_corners
#print axioms SquarePackingArchive.Nagamochi.continuous_score_gt_half_of_bottom_strip_missing_horizontal_corners
#print axioms SquarePackingArchive.Nagamochi.score_gt_nineteen_twentieths_of_bottom_strip_with_corner
#print axioms SquarePackingArchive.Nagamochi.resourceMeasure_preimage_swap
#print axioms SquarePackingArchive.Nagamochi.resourceMeasure_preimage_reflectY
#print axioms SquarePackingArchive.Nagamochi.resourceMeasure_preimage_reflectX
#print axioms SquarePackingArchive.NagamochiAugmentedResource.measure_univ
#print axioms SquarePackingArchive.NagamochiAugmentedResource.score_gt_one_of_fits
#print axioms SquarePackingArchive.Packing.squareCount_lt_squareMinusOne_of_side_lt
#print axioms SquarePackingArchive.Records.NearSquare.squareMinusOne_isMinimumSide
#print axioms SquarePackingArchive.Packing.squareMinusTwo_augmentedScore_budget
#print axioms SquarePackingArchive.Packing.squareMinusTwo_augmentedScore_lt_seven_fifths
#print axioms SquarePackingArchive.Packing.squareMinusTwo_not_two_bottom_points
#print axioms SquarePackingArchive.Packing.exists_squareMinusTwo_markedPoint_ownership
#print axioms SquarePackingArchive.Nagamochi.no_finite_disjoint_convex_neighbor_chain
#print axioms SquarePackingArchive.Nagamochi.upperCap_angle_bound_of_fits
#print axioms SquarePackingArchive.Nagamochi.no_crossing_exit_deficit_lt_half_cap_surplus
#print axioms SquarePackingArchive.Nagamochi.terminal_continuous_budget_of_fits
#print axioms SquarePackingArchive.Nagamochi.bottom_bad_square_crosses_next_boundary_band_positive_frame
#print axioms SquarePackingArchive.Nagamochi.chain_step_of_upper_facet_and_high_rightmost_vertex
#print axioms SquarePackingArchive.Nagamochi.common_upper_facet_of_two_missing_above_anchor
#print axioms SquarePackingArchive.Nagamochi.endpoint_two_height_continuous_budget_of_fits
#print axioms SquarePackingArchive.Nagamochi.edge_point_sides_equal_of_same_square
#print axioms SquarePackingArchive.Nagamochi.bottom_bad_square_starts_weighted_chain
#print axioms SquarePackingArchive.Nagamochi.finite_bottom_owner_chain_reaches_terminal_or_shared_owner
#print axioms SquarePackingArchive.Nagamochi.endpoint_two_height_score_budget_of_fits
#print axioms SquarePackingArchive.Nagamochi.corner_terminal_score_repays_incoming_height
#print axioms SquarePackingArchive.Nagamochi.not_adjacent_marked_points_of_missing_corner_segment
#print axioms SquarePackingArchive.Nagamochi.bad_square_has_exactly_one_corner_and_no_edge_points
#print axioms SquarePackingArchive.Packing.badSquares_card_le_eight
#print axioms SquarePackingArchive.finiteFamily_card_lt_resourceMass_of_balanced_transfers
#print axioms SquarePackingArchive.Packing.squareMinusTwo_impossible_of_scaled_fits
#print axioms SquarePackingArchive.Packing.squareMinusTwo_side_ge
#print axioms SquarePackingArchive.Records.NearSquare.squareMinusTwo_isMinimumSide
#print axioms SquarePackingArchive.Records.Square7.s7_lower_bound
#print axioms SquarePackingArchive.Records.Square7.s7_eq_three
#print axioms SquarePackingArchive.Records.NearSquare.s14_eq_four
#print axioms SquarePackingArchive.Records.NearSquare.s62_eq_eight
#print axioms SquarePackingArchive.Records.NearSquare.s79_eq_nine
#print axioms SquarePackingArchive.Records.NearSquare.s98_eq_ten
#print axioms SquarePackingArchive.Records.NearSquare.s63_eq_eight
#print axioms SquarePackingArchive.Records.NearSquare.s80_eq_nine
#print axioms SquarePackingArchive.Records.NearSquare.s99_eq_ten
#print axioms SquarePackingArchive.Nagamochi.bottom_grid_chord_at_least_side
#print axioms SquarePackingArchive.Nagamochi.originalLayout_scalar_mass_lower_bound
#print axioms SquarePackingArchive.Nagamochi.originalLayout_scalar_constraints_impossible
#print axioms SquarePackingArchive.Nagamochi.uniformDiagonal_scalar_constraints_impossible
#print axioms SquarePackingArchive.Nagamochi.originalLayout_variableArea_scalar_constraints_impossible
#print axioms SquarePackingArchive.Nagamochi.bottom_bad_square_misses_horizontal_corners
#print axioms SquarePackingArchive.Nagamochi.bottom_bad_square_location
#print axioms SquarePackingArchive.Nagamochi.bottom_bad_square_has_exactly_one_corner_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_nineteen_twentieths_of_bottom_strip
#print axioms SquarePackingArchive.Nagamochi.score_gt_three_halves_of_two_bottom_points
#print axioms SquarePackingArchive.Nagamochi.augmentedScore_gt_three_halves_of_two_bottom_points
#print axioms SquarePackingArchive.Records.SquareNumbers.squareNumber_isMinimumSide
#print axioms SquarePackingArchive.Records.SquareNumbers.s4_eq_two
#print axioms SquarePackingArchive.Records.SquareNumbers.s9_eq_three
#print axioms SquarePackingArchive.Records.SquareNumbers.s16_eq_four
#print axioms SquarePackingArchive.Records.SquareNumbers.s25_eq_five
#print axioms SquarePackingArchive.Records.SquareNumbers.s36_eq_six
#print axioms SquarePackingArchive.Records.SquareNumbers.s49_eq_seven
#print axioms SquarePackingArchive.Records.SquareNumbers.s64_eq_eight
#print axioms SquarePackingArchive.Records.SquareNumbers.s81_eq_nine
#print axioms SquarePackingArchive.Records.NearSquare.s2_eq_two
#print axioms SquarePackingArchive.Records.NearSquare.s3_eq_two
#print axioms SquarePackingArchive.Records.Square5.s5_le_goebel
#print axioms SquarePackingArchive.Records.Square5.unavoidable_points
#print axioms SquarePackingArchive.Records.Square5.s5_ge_goebel
#print axioms SquarePackingArchive.Records.Square5.s5_eq_goebel
#print axioms SquarePackingArchive.Records.Square8.contains_bottomLeftCorner
#print axioms SquarePackingArchive.Records.Square8.contains_bottomRightPair
#print axioms SquarePackingArchive.Records.Square8.contains_leftPair
#print axioms SquarePackingArchive.PlacedSquare.contains_triangleVertex
#print axioms SquarePackingArchive.PlacedSquare.contains_shortRectangleVertex
#print axioms SquarePackingArchive.PlacedSquare.contains_translatedShortRectangleVertex
#print axioms SquarePackingArchive.Records.Square8.points_unavoidable
#print axioms SquarePackingArchive.Records.Square8.s8_lower_bound
#print axioms SquarePackingArchive.Records.Square8.s8_eq_three
#print axioms SquarePackingArchive.Records.Square15.contains_bottomBand
#print axioms SquarePackingArchive.Records.Square15.contains_middleBand
#print axioms SquarePackingArchive.Records.Square15.contains_topBand
#print axioms SquarePackingArchive.Records.Square15.points_unavoidable
#print axioms SquarePackingArchive.Records.Square15.s15_lower_bound
#print axioms SquarePackingArchive.Records.Square15.s15_eq_four
#print axioms SquarePackingArchive.Records.Square24.points_unavoidable
#print axioms SquarePackingArchive.Records.Square24.s24_lower_bound
#print axioms SquarePackingArchive.Records.Square24.s24_eq_five
#print axioms SquarePackingArchive.StaggeredLattice.lowerBound
#print axioms SquarePackingArchive.Records.Square23.s23_eq_five
#print axioms SquarePackingArchive.Records.Square34.s34_eq_six
#print axioms SquarePackingArchive.Records.Square34.s35_eq_six
#print axioms SquarePackingArchive.PlacedSquare.scaleCenter_strictFits
#print axioms SquarePackingArchive.lowerBound_succ_of_strict_unavoidable
#print axioms SquarePackingArchive.Records.Square46.s46_eq_seven
#print axioms SquarePackingArchive.Records.Square46.s47_eq_seven
#print axioms SquarePackingArchive.Records.Square46.s48_eq_seven
#print axioms SquarePackingArchive.Records.Square11TrumpRationalized.s11_le_3_88
#print axioms SquarePackingArchive.Records.Square68.s68_le_8_80339
#print axioms SquarePackingArchive.Records.Square69.s69_le_8_8272
#print axioms SquarePackingArchive.HasPacking.enlarge
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s12_le_four
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s11_le_goebel_1979
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s11_le_hamalainen_1980
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s68_le_brendberg_2023
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s68_le_schadt_ellsworth_2025
#print axioms SquarePackingArchive.Records.HistoricalUpperBounds.s69_le_morandi_cantrell_2023
#print axioms SquarePackingArchive.PlacedSquare.rotateQuarter_contains_iff
#print axioms SquarePackingArchive.PlacedSquare.firstQuadrant_contains_iff
#print axioms SquarePackingArchive.Packing.side_positive
#print axioms SquarePackingArchive.Unavoidable.interior_scaled
#print axioms SquarePackingArchive.Packing.squareCount_le_of_interiorUnavoidable
#print axioms SquarePackingArchive.lowerBound_succ_of_interiorUnavoidable_below
#print axioms SquarePackingArchive.lowerBound_succ_of_unavoidable
#print axioms SquarePackingArchive.PlacedSquare.contains_unitCorner
#print axioms SquarePackingArchive.PlacedSquare.contains_cornerPoint
#print axioms SquarePackingArchive.PlacedSquare.contains_bottomPair
#print axioms SquarePackingArchive.PlacedSquare.contains_bottomPairWith
#print axioms SquarePackingArchive.PlacedSquare.contains_bottomBoundaryPair
#print axioms SquarePackingArchive.Frame.height_add_product_le_sum_of_height_le_sqrt_two_sub_half
#print axioms SquarePackingArchive.PlacedSquare.contains_bottomUnitPair
#print axioms SquarePackingArchive.moving_unavoidable_preserves_assignment
#print axioms SquarePackingArchive.Packing.squareCount_lt_resourceMass
#print axioms SquarePackingArchive.finiteFamily_card_lt_resourceMass
#print axioms SquarePackingArchive.NagamochiResource.measure_univ
#print axioms SquarePackingArchive.horizontalSegmentMeasure_lower_bound
#print axioms SquarePackingArchive.NagamochiResource.boundaryLines_subset_lower_bound
#print axioms SquarePackingArchive.NagamochiResource.innerArea_add_boundaryLines_le_measure
#print axioms SquarePackingArchive.NagamochiResource.cornerPoints_lower_bound_of_two_mem
#print axioms SquarePackingArchive.NagamochiResource.edgePoints_lower_bound_of_mem
#print axioms SquarePackingArchive.NagamochiResource.EdgePoint.cornerPoints_ne
#print axioms SquarePackingArchive.volume_rightTriangleProductRegion
#print axioms SquarePackingArchive.volume_rightTriangleRegion
#print axioms SquarePackingArchive.volume_translatedRightTriangleRegion
#print axioms SquarePackingArchive.volume_openTranslatedRightTriangleRegion
#print axioms SquarePackingArchive.openTranslatedRightTriangleRegion_subset_of_vertices_mem_closure
#print axioms SquarePackingArchive.volume_openOrientedTranslatedRightTriangleRegion
#print axioms SquarePackingArchive.openOrientedTranslatedRightTriangleRegion_subset_of_vertices_mem_closure
#print axioms SquarePackingArchive.closure_unitSquareInterior
#print axioms SquarePackingArchive.PlacedSquare.closure_interiorRegion
#print axioms SquarePackingArchive.PlacedSquare.mem_dilatedInteriorRegion_iff
#print axioms SquarePackingArchive.PlacedSquare.horizontalPoint_mem_swap_iff
#print axioms SquarePackingArchive.PlacedSquare.convex_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.dilatedCenterX_halfExtent_le
#print axioms SquarePackingArchive.PlacedSquare.dilatedCenterY_halfExtent_le
#print axioms SquarePackingArchive.PlacedSquare.unitCornerPoint_mem_dilatedInteriorRegion_of_center_le_one
#print axioms SquarePackingArchive.PlacedSquare.case5CornerPoints_mem_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.firstQuadrant_dilatedInteriorRegion_eq
#print axioms SquarePackingArchive.PlacedSquare.case5TopRightPoints_mem_dilatedInteriorRegion_any_frame
#print axioms SquarePackingArchive.PlacedSquare.horizontalCenterPoint_mem_dilatedInteriorRegion_any_frame
#print axioms SquarePackingArchive.PlacedSquare.topHorizontalCenterPoint_mem_dilatedInteriorRegion_any_frame
#print axioms SquarePackingArchive.PlacedSquare.rightVerticalCenterPoint_mem_dilatedInteriorRegion_any_frame
#print axioms SquarePackingArchive.PlacedSquare.horizontalChord_inside_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.horizontalAdjacentChord_inside_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.horizontalOtherAdjacentChord_inside_dilatedInteriorRegion
#print axioms SquarePackingArchive.PlacedSquare.horizontalOtherAdjacentChord_length
#print axioms SquarePackingArchive.PlacedSquare.horizontalCosineChord_length_at_least_factor
#print axioms SquarePackingArchive.PlacedSquare.horizontalSineChord_length_at_least_factor
#print axioms SquarePackingArchive.PlacedSquare.verticalSineChord_length_at_least_factor
#print axioms SquarePackingArchive.PlacedSquare.verticalCosineChord_length_at_least_factor
#print axioms SquarePackingArchive.Nagamochi.adjacentCut_triangleArea_lt_half_chord
#print axioms SquarePackingArchive.Nagamochi.centeredAdjacentChordLength_gt_one
#print axioms SquarePackingArchive.Nagamochi.Frame.exists_tangentHalfAngle_of_sine_le_cosine
#print axioms SquarePackingArchive.Nagamochi.horizontalAdjacentChord_length_gt_one
#print axioms SquarePackingArchive.Nagamochi.horizontalAdjacentChord_length_gt_one_any_positive_frame
#print axioms SquarePackingArchive.Nagamochi.cornerAdjacentChordLength_gt_one
#print axioms SquarePackingArchive.Nagamochi.horizontalOtherAdjacentChord_length_gt_one_of_bottom_contained
#print axioms SquarePackingArchive.Nagamochi.horizontalOtherAdjacentChord_length_gt_one
#print axioms SquarePackingArchive.Nagamochi.horizontalOtherAdjacentChord_length_gt_one_any_positive_frame
#print axioms SquarePackingArchive.Nagamochi.cornerCut_area_add_half_chord_gt_half
#print axioms SquarePackingArchive.Nagamochi.pinnedCut_score_gt_one
#print axioms SquarePackingArchive.Nagamochi.innerArea_lower_bound_of_translatedRightTriangle
#print axioms SquarePackingArchive.Nagamochi.innerArea_lower_bound_of_openTranslatedRightTriangle
#print axioms SquarePackingArchive.Nagamochi.innerArea_lower_bound_of_openOrientedTranslatedRightTriangle
#print axioms SquarePackingArchive.Nagamochi.pinnedCutTriangleRegion_subset_interiorRegion
#print axioms SquarePackingArchive.Nagamochi.pinnedCut_innerArea_lower_bound_of_triangle
#print axioms SquarePackingArchive.Nagamochi.PinnedCutTriangleWitness.innerArea_lower_bound
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_real_grouped_bounds
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_pinned_cut_bounds
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_pinned_cut_triangle_and_boundary_bound
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_pinned_cut_witness_and_boundary_bound
#print axioms SquarePackingArchive.Nagamochi.canonicalPinned_score_gt_one
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case6_corner_cut_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.boundaryChord_of_pointAt_mem
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_long_and_short_boundary_chords_and_corner_point
#print axioms SquarePackingArchive.Nagamochi.exists_nat_in_open_interval_of_length_gt_one
#print axioms SquarePackingArchive.Nagamochi.openGridChord_endpoint_bounds
#print axioms SquarePackingArchive.Nagamochi.longGridChordWitness_of_open_chord
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_centered_horizontalAdjacent
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_bottom_touching_horizontalOtherAdjacent
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_horizontalOpposite
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_axis_aligned
#print axioms SquarePackingArchive.Nagamochi.bottomLongGridChordWitness_of_center_in_bottom_strip
#print axioms SquarePackingArchive.Nagamochi.topLongGridChordWitness_of_center_in_top_strip
#print axioms SquarePackingArchive.Nagamochi.leftLongGridChordWitness_of_center_in_left_strip
#print axioms SquarePackingArchive.Nagamochi.rightLongGridChordWitness_of_center_in_right_strip
#print axioms SquarePackingArchive.Nagamochi.gridPointWitness_of_open_grid_chord
#print axioms SquarePackingArchive.Nagamochi.bottomGridPointWitness_of_center_in_bottom_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.gridPointWitness_of_center_in_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_edge_strip_long_chord_and_connections
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_edge_strip_long_chord_without_grid_corners
#print axioms SquarePackingArchive.Nagamochi.corner_mem_of_gridPointWitness_of_no_edge_points
#print axioms SquarePackingArchive.Nagamochi.edge_mem_of_gridPointWitness_of_no_corner_points
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_dilatedInteriorRegion_subset_innerArea
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_compensated_inner_area
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case5_resource_bounds
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_unitCornerPoint_mem
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case5_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case5_any_frame
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case5
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_bottom_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_top_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_left_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_right_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.innerArea_positive_of_edge_strip_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_resource_witness
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_two_boundary_corner_points
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_first_boundary_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_second_boundary_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_long_chord_and_grid_point
#print axioms SquarePackingArchive.Nagamochi.case7ResourceWitness_of_long_chord_and_boundary_connection
#print axioms SquarePackingArchive.Nagamochi.firstBoundaryCornerConnection_of_mem
#print axioms SquarePackingArchive.Nagamochi.secondBoundaryCornerConnection_of_mem
#print axioms SquarePackingArchive.Nagamochi.case7EdgeStripOutcome_of_long_chord
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_opposite_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_bottom_opposite_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_first_boundary_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_second_boundary_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_bottom_corner_and_edge_point
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_two_boundary_corner_points_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case7_both_bottom_corner_points_geometry
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_two_boundaryLine_chords
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_half_area_and_boundary_chord
#print axioms SquarePackingArchive.Nagamochi.boundaryChord_of_opposite
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_two_opposite_boundary_chords
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case3_resource_witness
#print axioms SquarePackingArchive.PlacedSquare.centralReflection_mem_dilatedInteriorRegion_iff
#print axioms SquarePackingArchive.PlacedSquare.half_volume_le_volume_innerHalfSpace
#print axioms SquarePackingArchive.Nagamochi.half_innerArea_of_single_inner_boundary_crossing
#print axioms SquarePackingArchive.Nagamochi.inward_bounds_of_center_inside_and_no_crossing
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case3_single_crossed_line
#print axioms SquarePackingArchive.Nagamochi.exists_horizontal_chord_of_center_offset_le
#print axioms SquarePackingArchive.Nagamochi.exists_horizontal_chord_of_axis_aligned
#print axioms SquarePackingArchive.Nagamochi.firstQuadrant_frame_difference
#print axioms SquarePackingArchive.Nagamochi.exists_horizontal_chord_of_center_offset_le_any_frame
#print axioms SquarePackingArchive.Nagamochi.exists_boundary_line_chord_of_center_offset_le
#print axioms SquarePackingArchive.Nagamochi.boundaryChord_of_line_chord_and_other_sides_inside
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_case3_single_crossed_line_offset
#print axioms SquarePackingArchive.Nagamochi.horizontalLowerCap_compensated
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_single_bottom_crossing
#print axioms SquarePackingArchive.Nagamochi.boundaryCut_compensated_of_adjacent
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_adjacent_boundary_cuts
#print axioms SquarePackingArchive.Nagamochi.innerHalfArea_add_otherBoundaryCuts_covers_square
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_long_chord_and_adjacent_boundary_cuts
#print axioms SquarePackingArchive.Nagamochi.exists_active_boundary_of_outside
#print axioms SquarePackingArchive.Nagamochi.boundaryLine_clipped_of_active_and_missing_corners
#print axioms SquarePackingArchive.Nagamochi.center_inner_missing_corners_does_not_imply_full_line_clipping
#print axioms SquarePackingArchive.Nagamochi.horizontal_cut_classification
#print axioms SquarePackingArchive.Nagamochi.inner_boundary_cut_classification
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_center_inner_cut_budgets
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_center_inner_without_corners
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_center_inner
#print axioms SquarePackingArchive.Nagamochi.deformationCounterexample_mem_iff
#print axioms SquarePackingArchive.Nagamochi.deformationCounterexample_inside_container
#print axioms SquarePackingArchive.Nagamochi.deformationCounterexample_fits
#print axioms SquarePackingArchive.Nagamochi.deformationCounterexample_closed_dilation_fits
#print axioms SquarePackingArchive.Nagamochi.deformationCounterexample_score_le
#print axioms SquarePackingArchive.Nagamochi.not_scoresDilatedSquares_four
#print axioms SquarePackingArchive.Nagamochi.score_gt_one_of_bottom_top_horizontalOpposite
#print axioms SquarePackingArchive.Packing.squareCount_lt_nagamochiMass
#print axioms SquarePackingArchive.Records.NearSquare.squareMinusTwo_isMinimumSide_of_nagamochiScores
